--assingnment one(day 2)
--Q1 Retrieve all columns from the customer table.
select *
from customer;

--Q2 Display only film_id, title, and rating from the film table.
select film_id, title, rating
from film;

--Q3 Retrieve the first 15 records from the actor table.
select *
from actor
limit 15;

--Q4 Retrieve all customers and sort them by last_name in ascending order.
select *
from customer
order by last_name asc;

--Q5 Display payment_id, customer_id, and amount, sorted by amount from lowest to highest.
select payment_id, customer_id, amount
from payment
order by amount asc;

--Q6 Retrieve customers sorted by:
    -- first_name in ascending order
    -- last_name in descending order
select *
from customer
order by first_name asc, last_name desc;

--Q7 Retrieve all payments where the amount is greater than 5.
select *
from payment
where amount > 5;

--Q8 Retrieve all payments where the amount is between 3.99 and 6.99.
select *
from payment
where amount between 3.99 and 6.99;

--Q9 Retrieve all customers whose first_name starts with the letter J.
select *
from customer
where first_name like 'J%'; 

--Q10 Retrieve all films where the description contains the word “Action”.
select *
from film
where description like  '%Action%';

--Q11 Retrieve payments greater than 7, sorted by amount in descending order.
select *
from payment
where amount > 7
order by amount desc;

--Q12 Retrieve customers whose first name ends with “n”, sorted alphabetically.
select *
from customer
where first_name like '%n'
order by first_name asc;

--Q13 Calculate the total amount spent by each customer.
select customer_id, sum(amount) as total_amount
from payment
group by customer_id;

--Q14 Retrieve the average payment amount per customer.
select customer_id, avg(amount) as Average_amount
from payment
group by customer_id;

--Q15 Calculate the total revenue generated by each staff member.
select staff_id, sum(amount) as generated_revenue
from payment
group by staff_id;

--Q16 Identify the top 5 customers based on total payment amount.
select customer_id, sum(amount) as total_amount
from payment
group by customer_id
order by total_amount desc
limit 5;

--Q17 Find the average film length per release year.
select release_year, avg(length) as average_length
from film
group by release_year;

--Q18 Retrieve the highest single payment amount in the payment table.
select max(amount) as highest_amount
from payment;

--Q19 Count how many payments each customer has made.
select customer_id, count(payment_id) as payment_made
from payment
group by customer_id;

--Q20 Retrieve customers who are active and sort them by first_name.
select *
from customer
where active = 1
order by first_name asc;